In [1]:
import numpy as np
list1=[0,1,2,3,4] #this is a list
arr=np.array(list1) #convert list into array
print(arr)
arr=arr+2 # we can add number 2 but this number add to each number of array without changing its size 
print(arr)
list1=list1+2 # but we cannot add any number in list

[0 1 2 3 4]
[2 3 4 5 6]


TypeError: can only concatenate list (not "int") to list

In [ ]:
# array is same like as list. we can change the size of list by adding another list  but we can't change the size of list.
#array can be used by importing numpy & list is built in python
#assertion & deletion in list easier but array assertion & deletion in array complex
#array is fix in size but list is dynamic
#array store homogenous(same kind) data & list store hetrogenous(different kind) data

In [3]:
list2=[[0,1,4],[4,5,6],[9,9,0]]
arr1=np.array(list2) # convert list into arry using numpy here we convert list of lists into 2d_array(row&columns)
print(arr1)

[[0 1 4]
 [4 5 6]
 [9 9 0]]


In [5]:
arr2=np.array(list2,dtype='float') # we we can specify data type by using the dtype() argument
print(arr2)

[[0. 1. 4.]
 [4. 5. 6.]
 [9. 9. 0.]]


In [7]:
arr2=np.array(list2,dtype='str') # we we can specify data type by using the dtype() _1.(argument for one data type)
print(arr2)

[['0' '1' '4']
 ['4' '5' '6']
 ['9' '9' '0']]


In [15]:
arr3=arr2.astype('int').astype('str') # astype() argument is used to combine two data types 
print(arr3)

[['0' '1' '4']
 ['4' '5' '6']
 ['9' '9' '0']]


In [17]:
arr3=arr2.astype('int').astype('float')
print(arr3)

[[0. 1. 4.]
 [4. 5. 6.]
 [9. 9. 0.]]


In [19]:
arr3=arr1.astype('int').astype('float')
print(arr3)

[[0. 1. 4.]
 [4. 5. 6.]
 [9. 9. 0.]]


In [21]:
arr2=np.array(list2,dtype='object') # we we can specify data type by using the dtype() argument
print(arr2)

[[0 1 4]
 [4 5 6]
 [9 9 0]]


In [25]:
arr4=np.array([1,'b'],dtype='object') # we can add object type data( characters and numbers) in array
print(arr4)

[1 'b']


In [27]:
arr5=arr4.tolist() #we convert array into list by using tolist() command.
print(arr5)

[1, 'b']


In [29]:
list5=[[0,7,8],[5,6,7],[1,2,3]]
arr6=np.array(list5,dtype='float') #convert to suggested dara type
print('shape:',arr6.shape) # tell the the no.s of how many rows and columns
print('Data type:',arr6.dtype) # tell the data type
print('size:',arr6.size) # tell the  size that how many totals entries in a array
print('num dimension:',arr6.ndim) # tell the dimension of array

shape: (3, 3)
Data type: float64
size: 9
num dimension: 2


In [33]:
list5=[[0,7,8],[5,6,7],[1,2,3]]
arr6=np.array(list5,dtype='float')
print('whole:',arr6) # print whole array 
print('part:',arr6[:2,:2]) # print some part of array [no.s of list,no.s of entries in a list]

whole: [[0. 7. 8.]
 [5. 6. 7.]
 [1. 2. 3.]]
part: [[0. 7.]
 [5. 6.]]


In [35]:
list5=[[0,7,8],[5,6,7],[1,2,3]]
arr6=np.array(list5,dtype='float')
print('whole:',arr6)
print('part:',arr6[:1,:2]) # print some part of array [no.s of list,no.s of entries in a list]

whole: [[0. 7. 8.]
 [5. 6. 7.]
 [1. 2. 3.]]
part: [[0. 7.]]


In [41]:
list5=[[0,7,8],[5,6,7],[1,2,3]]
arr6=np.array(list5,dtype='float')
boo=arr6
print(boo)

[[0. 7. 8.]
 [5. 6. 7.]
 [1. 2. 3.]]


In [43]:
list5=[[0,7,8],[5,6,7],[1,2,3]]
arr6=np.array(list5,dtype='float')
boo=arr6>2 # remember
print(boo) # convert into boolean(False&True)

[[False  True  True]
 [ True  True  True]
 [False False  True]]


In [ ]:
#pandas store the data in tabular(table) form like data_Frame.
#pandas used two data structures(1.Series & 2.Data Frames)
#series is same as list but but series associates a lebel with each element.This makes it look like a dictionary.
#series extract all values in the series ,as well as indiviual elements by index.
# Data frame is a table with rows and columns.
#each column in a data is series.
#series is used to combine a data frame.
#rows consist of elements inside series.
#pandas data frames can be constructed using python dictionary.

In [47]:
import pandas as pd
series1=pd.Series([1,2,3,4,5])  # 's' must be capital in Series
print(series1)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [49]:
series1=pd.Series([1,2,3,4,5])
print(series1.values)
print('____________')
print(series1[3])
print(series1[4])

[1 2 3 4 5]
____________
4
5


In [55]:
series1=pd.Series([1,2,3,4,5],index=['a','b','c','g','t']) # we can also provide an index manually by characters.
print(series1.values)
print('____________')
print(series1['g']) # same sample with courts use must remember
print(series1['t'])

[1 2 3 4 5]
____________
4
5


In [59]:
series1=pd.Series([1,2,3,4,5],index=['a','b','c','g','t']) # we can also provide an index manually by characters.
print(series1.values)
print(series1)
print('____________')
series1[['a','c','g']]=0 #we retrieve several elements of a series by their indices or make group assignment
print(series1)

[1 2 3 4 5]
a    1
b    2
c    3
g    4
t    5
dtype: int64
____________
a    0
b    2
c    0
g    0
t    5
dtype: int64


In [61]:
df=pd.DataFrame({
    'countary':['Russia','Pakistan','India','ukraine'],
    'population':[12.9,143,300.98,78.45],
    'disease':['aids','paralysis','hepatite','migrane']}) # data frame by using dictionary
print(df)

   countary  population    disease
0    Russia       12.90       aids
1  Pakistan      143.00  paralysis
2     India      300.98   hepatite
3   ukraine       78.45    migrane


In [69]:
list2=[[0,1,4],[4,5,6],[9,9,0]]
df1=pd.DataFrame(list2) # if we don't give columns name then pandas automatically developed named of columns in numeric form(0,1,3...)
print(df1)
df1.columns=['A1','A2','A3'] # we can give the names to columns    
print(df1)


   0  1  2
0  0  1  4
1  4  5  6
2  9  9  0
   A1  A2  A3
0   0   1   4
1   4   5   6
2   9   9   0


In [71]:
list2=[[0,1,4],[4,5,6],[9,9,0]]
df1=pd.DataFrame(list2) # if we don't give columns& roms name then pandas automatically developed named of columns&rows in numeric form(0,1,3...) from 0 to N-1
print(df1)
print('____________')
df1.columns=['A1','A2','A3'] # we can give the names to columns 
print(df1)


   0  1  2
0  0  1  4
1  4  5  6
2  9  9  0
____________
   A1  A2  A3
0   0   1   4
1   4   5   6
2   9   9   0


In [89]:
df=pd.DataFrame({
    'countary':['Russia','Pakistan','India','ukraine'],
    'population':[12.9,143,300.98,78.45],
    'disease':['aids','paralysis','hepatite','migrane']}) # data frame by using dictionary
print(type(df['countary'])) # each column in a data frame is series.
print(df.columns)# gives columns names
print("_______")
print(df.index)# (give column and row index starting from 0, to stop at N-1 ,increase adding one element in next to next)

<class 'pandas.core.series.Series'>
Index(['countary', 'population', 'disease'], dtype='object')
_______
RangeIndex(start=0, stop=4, step=1)


In [91]:
# another way to provide row indices explicitly.
df=pd.DataFrame({
    'countary':['Russia','Pakistan','India','ukraine'],
    'population':[12.9,143,300.98,78.45],
    'disease':['aids','paralysis','hepatite','migrane']},index=['RAS','PAK','IND','UK']) # data frame by using dictionary
print(df)


     countary  population    disease
RAS    Russia       12.90       aids
PAK  Pakistan      143.00  paralysis
IND     India      300.98   hepatite
UK    ukraine       78.45    migrane


In [93]:
# how do it during runtime
df=pd.DataFrame({
    'countary':['Russia','Pakistan','India','ukraine'],
    'population':[12.9,143,300.98,78.45],
    'disease':['aids','paralysis','hepatite','migrane']}) # data frame by using dictionary
print(df)
print('___________')
df.index=['RAS','PAK','IND','UK'] # index for rows
df.index.name='countary obv'# column name for rows element
print(df)

   countary  population    disease
0    Russia       12.90       aids
1  Pakistan      143.00  paralysis
2     India      300.98   hepatite
3   ukraine       78.45    migrane
___________
              countary  population    disease
countary obv                                 
RAS             Russia       12.90       aids
PAK           Pakistan      143.00  paralysis
IND              India      300.98   hepatite
UK             ukraine       78.45    migrane


In [99]:
#we can access on whole row . we can use .loc() and provide an index label.
print(df.loc['PAK'])
print('_________')
#Second,we can access on whole row . we can use .iloc() and provide an index number.
print(df.iloc[0])


countary       Pakistan
population        143.0
disease       paralysis
Name: PAK, dtype: object
_________
countary      Russia
population      12.9
disease         aids
Name: RAS, dtype: object


In [103]:
#a selection of perticular rows columns can be selected this way 
print(df.loc[['PAK','IND'],'population'])

countary obv
PAK    143.00
IND    300.98
Name: population, dtype: float64


In [107]:
#slicing of data frame 
print(df.loc['PAK':'IND',:])

              countary  population    disease
countary obv                                 
PAK           Pakistan      143.00  paralysis
IND              India      300.98   hepatite


In [117]:
df=pd.DataFrame({
    'countary':['Russia','Pakistan','India','ukraine'],
    'population':[12.9,143,300.98,78.45],
    'disease':['aids','paralysis','hepatite','migrane']})
# .drop() function is use to drop any column in data frame
print(df)
print('____________')
df=df.drop(['population'],axis='columns') # use to drop population column
print(df)

   countary  population    disease
0    Russia       12.90       aids
1  Pakistan      143.00  paralysis
2     India      300.98   hepatite
3   ukraine       78.45    migrane
____________
   countary    disease
0    Russia       aids
1  Pakistan  paralysis
2     India   hepatite
3   ukraine    migrane
